In [5]:
import numpy as np

In [43]:
x1=np.linspace(0,1,50)
x1

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [49]:
x2=np.linspace(0,1,20).reshape((4,5))
x2

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [50]:
first,second,third=np.vsplit(x2,(2,4))
print("The first split \n",first,"\n")
print("The second split \n",second,"\n")
print("The third split \n",third)

The first split 
 [[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]] 

The second split 
 [[0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]] 

The third split 
 []


In [47]:
first,second,third=np.split(x1,(15,30))
print("The first split \n",first)
print()
print("The second split \n",second,"\n")
print("The third split \n",third)

The first split 
 [0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429]

The second split 
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551  0.40816327
 0.42857143 0.44897959 0.46938776 0.48979592 0.51020408 0.53061224
 0.55102041 0.57142857 0.59183673] 

The third split 
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [51]:
x3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
x3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
x4=np.random.normal(0,1,(4,5))
x4

array([[-0.2030929 ,  0.03697535,  0.20983553, -0.28951594, -1.74185489],
       [ 0.34044914, -0.26830502, -0.36257412,  1.05203468, -0.74618573],
       [ 0.06461081,  1.32052702,  0.50154759, -1.30112769, -0.13074332],
       [ 1.49170416, -0.89426456,  0.53599693, -0.94982881,  0.27791096]])

In [53]:
x5=np.ones((4,5),dtype=int)
x5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#ASSIGNMENT TWO

In [ ]:
#use us_births data to compute the following using np:
    #extract the year, gender and births column from the data
    #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
    #compute the maximum births and minimum births
    #indicate the gender with minimum birth and maximum birth
    #indicate the year with minimum birth and maximum birth

In [17]:
import pandas as pd
us_birth_data = pd.read_csv('C:\\pythonClass\\DataSet\\us_births.csv')
us_birth_data.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [18]:
# Extracting year, gender and births column from the data.
us_year = np.array(us_birth_data['year'])
us_gender = np.array(us_birth_data['gender'])
us_births = np.array(us_birth_data['births'])
print("US Year\n",us_year,"\n")
print("US Gender\n",us_gender,"\n")
print("US Births\n",us_births)

US Year
 [1969 1969 1969 ... 2008 2008 2008] 

US Gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

US Births
 [  4046   4440   4454 ... 165468 173215 181235]


In [38]:
# compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
print("Total Birth:   ", us_births.sum())
print("Mean of Birth:   ", us_births.mean())
print("Median Birth:   ", np.median(us_births))
print("-------------------------------------------------")
print("Total Female:   ", us_births[us_gender=="F"].sum())
print("Mean of Female:   ", us_births[us_gender=="F"].mean())
print("Median of Female:   ", np.median(us_births[us_gender=="F"]))
print("-------------------------------------------------")
print("Total Male:   ", us_births[us_gender=="M"].sum())
print("Mean of Male:   ", us_births[us_gender=="M"].mean())
print("Median of Male:   ", np.median(us_births[us_gender=="M"]))

Total Birth:    151774378
Mean of Birth:    9762.293561458802
Median Birth:    4814.0
-------------------------------------------------
Total Female:    74035823
Mean of Female:    9521.067772633745
Median of Female:    4688.5
-------------------------------------------------
Total Male:    77738555
Mean of Male:    10003.674559258783
Median of Male:    4938.0


In [39]:
#compute the maximum births and minimum births
print("Minimum birth:   ", us_births.min())
print("Maximum birth:   ", us_births.max())

minimum birth:    1
maximum birth:    199622


In [41]:
#indicate the gender with minimum birth and maximum birth
print("Gender With Minimum Birth:   ", us_gender[us_births.argmin()])
print("Gender With Maximum Birth:   ", us_gender[us_births.argmax()])

Gender With Minimum Birth:    F
Gender With Maximum Birth:    M


In [42]:
#indicate the year with minimum birth and maximum birth
print("Year With Minimum Birth:   ", us_year[us_births.argmin()])
print("Year With Maximum Birth:   ", us_year[us_births.argmax()])

Year With Minimum Birth:    1975
Year With Maximum Birth:    2007
