In [2]:
import numpy as np

In [3]:
x1=np.linspace(0,1,50)
x1

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [49]:
x2=np.linspace(0,1,20).reshape((4,5))
x2

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [50]:
first,second,third=np.vsplit(x2,(2,4))
print("The first split \n",first,"\n")
print("The second split \n",second,"\n")
print("The third split \n",third)

The first split 
 [[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]] 

The second split 
 [[0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]] 

The third split 
 []


In [47]:
first,second,third=np.split(x1,(15,30))
print("The first split \n",first)
print()
print("The second split \n",second,"\n")
print("The third split \n",third)

The first split 
 [0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429]

The second split 
 [0.30612245 0.32653061 0.34693878 0.36734694 0.3877551  0.40816327
 0.42857143 0.44897959 0.46938776 0.48979592 0.51020408 0.53061224
 0.55102041 0.57142857 0.59183673] 

The third split 
 [0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [51]:
x3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
x3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
x4=np.random.normal(0,1,(4,5))
x4

array([[-0.2030929 ,  0.03697535,  0.20983553, -0.28951594, -1.74185489],
       [ 0.34044914, -0.26830502, -0.36257412,  1.05203468, -0.74618573],
       [ 0.06461081,  1.32052702,  0.50154759, -1.30112769, -0.13074332],
       [ 1.49170416, -0.89426456,  0.53599693, -0.94982881,  0.27791096]])

In [53]:
x5=np.ones((4,5),dtype=int)
x5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#ASSIGNMENT TWO

In [ ]:
#use us_births data to compute the following using np:
    #extract the year, gender and births column from the data
    #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
    #compute the maximum births and minimum births
    #indicate the gender with minimum birth and maximum birth
    #indicate the year with minimum birth and maximum birth

In [17]:
import pandas as pd
us_birth_data = pd.read_csv('C:\\pythonClass\\DataSet\\us_births.csv')
us_birth_data.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [18]:
# Extracting year, gender and births column from the data.
us_year = np.array(us_birth_data['year'])
us_gender = np.array(us_birth_data['gender'])
us_births = np.array(us_birth_data['births'])
print("US Year\n",us_year,"\n")
print("US Gender\n",us_gender,"\n")
print("US Births\n",us_births)

US Year
 [1969 1969 1969 ... 2008 2008 2008] 

US Gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

US Births
 [  4046   4440   4454 ... 165468 173215 181235]


In [38]:
# compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
print("Total Birth:   ", us_births.sum())
print("Mean of Birth:   ", us_births.mean())
print("Median Birth:   ", np.median(us_births))
print("-------------------------------------------------")
print("Total Female:   ", us_births[us_gender=="F"].sum())
print("Mean of Female:   ", us_births[us_gender=="F"].mean())
print("Median of Female:   ", np.median(us_births[us_gender=="F"]))
print("-------------------------------------------------")
print("Total Male:   ", us_births[us_gender=="M"].sum())
print("Mean of Male:   ", us_births[us_gender=="M"].mean())
print("Median of Male:   ", np.median(us_births[us_gender=="M"]))

Total Birth:    151774378
Mean of Birth:    9762.293561458802
Median Birth:    4814.0
-------------------------------------------------
Total Female:    74035823
Mean of Female:    9521.067772633745
Median of Female:    4688.5
-------------------------------------------------
Total Male:    77738555
Mean of Male:    10003.674559258783
Median of Male:    4938.0


In [39]:
#compute the maximum births and minimum births
print("Minimum birth:   ", us_births.min())
print("Maximum birth:   ", us_births.max())

minimum birth:    1
maximum birth:    199622


In [41]:
#indicate the gender with minimum birth and maximum birth
print("Gender With Minimum Birth:   ", us_gender[us_births.argmin()])
print("Gender With Maximum Birth:   ", us_gender[us_births.argmax()])

Gender With Minimum Birth:    F
Gender With Maximum Birth:    M


In [42]:
#indicate the year with minimum birth and maximum birth
print("Year With Minimum Birth:   ", us_year[us_births.argmin()])
print("Year With Maximum Birth:   ", us_year[us_births.argmax()])

Year With Minimum Birth:    1975
Year With Maximum Birth:    2007


In [53]:
#ASSIGNMENT THREE

In [54]:
#Using the BicycleWeather.csv dataset perform the following operations:
#    1. Extract the PRCP column from the pandas object.
#    2. Using boolean functions/operators separate numbers from NAN
#    3. Using boolean masking separate all zeros and non-zeros into different variables.
#    4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
#    5. Calculate the following:
#        a. Median precip on rainy days
#        b. Median precip on summer days 
#        c. Maximum precip on summer days 
#        d. Median precip on non-summer rainy days

In [55]:
import pandas as pd
bicycle = pd.read_csv('C:\\pythonClass\\DataSet\\BicycleWeather.csv')
bicycle.head()

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  ...  WT17  WT05  WT02  WT22  \
0     0     0     0   128    50    47   100  ... -9999 -9999 -9999 -9999   
1   109     0     0   106    28    45   180  ... -9999 -9999 -9999 -9999   
2     8     0     0   117    72    23   180  ... -9999 -9999 -9999 -9999   
3   203     0     0   122    56    47   180  ... -9999 -9999 -9999 -9999   
4    13     0     0    89    28    61   200  ... -9999 -9999 -9999 -9999   

   WT04  WT13  WT16  WT08  WT18  WT03  
0 -9999 -9999 -9999 -9999 -9999 -9999  
1 -9999     1     1 -9999 -9999 -9999  
2 -9999 -9999     1 -9999 -9999 -9999  
3 -9999     1     1 -9999 -9999 -9999  
4 -9999 -9999     1 -9999 -9999 -9999  

[5 rows x 26 columns]

In [56]:
#    1. Extract the PRCP column from the pandas object.
weathers = bicycle['PRCP'].values
weathers

array([  0, 109,   8, ..., 102,   0,  58], dtype=int64)

In [57]:
inches = weathers/254 # 1/10mm =inches
inches

array([0.        , 0.42913386, 0.03149606, ..., 0.4015748 , 0.        ,
       0.22834646])

In [58]:
#    2. Using boolean functions/operators separate numbers from NAN
inches
val = pd.notna(inches)
inches[val]

array([0.        , 0.42913386, 0.03149606, ..., 0.4015748 , 0.        ,
       0.22834646])

In [59]:
#    3. Using boolean masking separate all zeros and non-zeros into different variables.
weather =inches[val]
print("Printing the zero values")
zeroweather = (weather == 0)
weather[zeroweather]

Printing the zero values


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [60]:
#    3. Using boolean masking separate all zeros and non-zeros into different variables.
print("Printing the n0n-zero values")
nonzeroweather = (weather > 0)
weather[nonzeroweather]

Printing the n0n-zero values


array([0.42913386, 0.03149606, 0.7992126 , 0.0511811 , 0.0984252 ,
       0.16929134, 0.03937008, 0.16141732, 0.20866142, 0.0984252 ,
       0.31889764, 0.77952756, 0.5984252 , 0.53149606, 0.11811024,
       0.24015748, 0.33858268, 0.31889764, 0.18897638, 1.09055118,
       0.14173228, 0.07086614, 0.53149606, 0.01181102, 0.11023622,
       0.0984252 , 0.0984252 , 0.03149606, 0.03937008, 0.4488189 ,
       0.0984252 , 0.07086614, 0.68110236, 0.2519685 , 0.11811024,
       0.03149606, 0.33858268, 0.4488189 , 0.0511811 , 0.14173228,
       0.03149606, 0.07874016, 0.27165354, 0.01968504, 0.14173228,
       0.40944882, 0.53937008, 0.75984252, 0.37007874, 0.33858268,
       0.94094488, 0.33070866, 0.37007874, 0.14173228, 0.07874016,
       0.14173228, 0.0511811 , 0.16141732, 0.18897638, 0.0511811 ,
       1.07874016, 0.22047244, 0.51968504, 0.05905512, 0.05905512,
       0.18110236, 0.01181102, 0.09055118, 0.01968504, 0.31889764,
       0.07086614, 0.07086614, 0.42913386, 0.25984252, 0.16929

In [61]:
#    4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
nonzeroweather_mul = (weather > 0) 
weather[nonzeroweather_mul] * 100

array([ 42.91338583,   3.1496063 ,  79.92125984,   5.11811024,
         9.84251969,  16.92913386,   3.93700787,  16.14173228,
        20.86614173,   9.84251969,  31.88976378,  77.95275591,
        59.84251969,  53.1496063 ,  11.81102362,  24.01574803,
        33.85826772,  31.88976378,  18.8976378 , 109.05511811,
        14.17322835,   7.08661417,  53.1496063 ,   1.18110236,
        11.02362205,   9.84251969,   9.84251969,   3.1496063 ,
         3.93700787,  44.88188976,   9.84251969,   7.08661417,
        68.11023622,  25.19685039,  11.81102362,   3.1496063 ,
        33.85826772,  44.88188976,   5.11811024,  14.17322835,
         3.1496063 ,   7.87401575,  27.16535433,   1.96850394,
        14.17322835,  40.94488189,  53.93700787,  75.98425197,
        37.00787402,  33.85826772,  94.09448819,  33.07086614,
        37.00787402,  14.17322835,   7.87401575,  14.17322835,
         5.11811024,  16.14173228,  18.8976378 ,   5.11811024,
       107.87401575,  22.04724409,  51.96850394,   5.90

In [62]:
#    4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
nonzeroweather_mul = (weather > 0) 
weather[nonzeroweather_mul] / 250
weather

array([0.        , 0.42913386, 0.03149606, ..., 0.4015748 , 0.        ,
       0.22834646])

In [63]:
summ1=weather[:365]
summ1

array([0.        , 0.42913386, 0.03149606, 0.7992126 , 0.0511811 ,
       0.0984252 , 0.        , 0.        , 0.16929134, 0.03937008,
       0.        , 0.        , 0.        , 0.16141732, 0.20866142,
       0.0984252 , 0.31889764, 0.77952756, 0.5984252 , 0.53149606,
       0.11811024, 0.24015748, 0.        , 0.33858268, 0.31889764,
       0.18897638, 0.        , 0.        , 1.09055118, 0.14173228,
       0.07086614, 0.53149606, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01181102, 0.11023622, 0.0984252 ,
       0.0984252 , 0.03149606, 0.03937008, 0.4488189 , 0.0984252 ,
       0.        , 0.07086614, 0.68110236, 0.2519685 , 0.        ,
       0.11811024, 0.03149606, 0.33858268, 0.        , 0.4488189 ,
       0.        , 0.0511811 , 0.        , 0.14173228, 0.03149606,
       0.        , 0.07874016, 0.        , 0.        , 0.27165354,
       0.01968504, 0.        , 0.        , 0.14173228, 0.40944882,
       0.53937008, 0.75984252, 0.37007874, 0.33858268, 0.94094

In [64]:
summ2=weather[366:731]
summ2

array([0.        , 0.        , 0.16141732, 0.0984252 , 0.11811024,
       0.07874016, 0.09055118, 0.64173228, 1.51181102, 0.01181102,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.2007874 , 0.22834646, 0.11811024,
       0.09055118, 0.07086614, 0.31102362, 0.16929134, 0.14173228,
       0.11811024, 0.01181102, 0.        , 0.09055118, 0.        ,
       0.12992126, 0.03937008, 0.0511811 , 0.        , 0.01181102,
       0.        , 0.01181102, 0.03937008, 0.09055118, 0.03937008,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05905512, 0.01968504, 0.37007874, 0.01181102, 0.        ,
       0.09055118, 0.01968504, 0.18110236, 0.31889764, 0.16141732,
       0.03149606, 0.        , 0.        , 0.        , 0.46850394,
       0.29133858, 0.        , 0.        , 0.03149606, 0.0511811 ,
       0.07874016, 0.09055118, 0.11023622, 0.        , 0.16929

In [65]:
summ3=weather[732:1097]
summ3

array([0.16141732, 0.05905512, 0.        , 0.        , 0.01181102,
       0.48031496, 0.38188976, 0.22834646, 0.16929134, 0.83858268,
       0.05905512, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01968504, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.3503937 , 0.8503937 , 0.        , 0.09055118,
       0.07874016, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.2007874 , 0.01968504, 0.72047244,
       0.66929134, 0.18110236, 0.07086614, 0.37007874, 0.46062992,
       1.03937008, 0.57086614, 0.5984252 , 0.03937008, 0.11811024,
       0.11023622, 0.0984252 , 0.24015748, 0.51181102, 0.01181102,
       0.        , 0.        , 0.        , 0.01968504, 0.7519685 ,
       0.42125984, 0.6496063 , 1.83858268, 0.11811024, 0.        ,
       1.27165354, 0.16929134, 0.74015748, 0.        , 0.        ,
       0.01968504, 0.27165354, 0.31889764, 1.09055118, 0.01181

In [66]:
summ4=weather[1098:]
summ4

array([0.        , 0.4015748 , 0.31889764, 0.        , 0.        ,
       0.        , 0.01181102, 0.22834646, 0.05905512, 0.        ,
       0.        , 0.        , 0.38188976, 0.        , 1.03149606,
       0.83858268, 0.01968504, 0.        , 0.        , 0.03149606,
       0.22834646, 0.01968504, 0.        , 0.        , 0.03149606,
       0.        , 0.        , 0.        , 0.        , 0.05905512,
       0.29133858, 0.0511811 , 0.33070866, 1.03149606, 0.68110236,
       0.92913386, 0.14173228, 0.24015748, 0.01181102, 0.        ,
       0.03937008, 0.        , 0.01181102, 0.        , 0.        ,
       0.        , 0.        , 0.18110236, 0.03149606, 0.        ,
       0.        , 0.        , 0.        , 0.16141732, 0.37007874,
       0.72047244, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03149606, 0.0984252 , 0.        , 0.07874016,
       0.66929134, 2.2007874 , 0.03937008, 0.03149606, 0.     

In [94]:
print("Median precip on rainy days (inches): ", np.median(weather[nonzeroweather_mul]))
print("Median precip on summer days (inches): ", np.median(summ1[summer]))
print("Maximum precip on summer days (inches): ", np.max(summ1[summer]))
summ1_rainy=summ1>0
print("Median precip on non-summer rainy days (inches): ", np.median(summ1[summ1_rainy & ~summer]))

Median precip on rainy days (inches):  0.14960629921259844
Median precip on summer days (inches):  0.0
Maximum precip on summer days (inches):  0.6181102362204725
Median precip on non-summer rainy days (inches):  0.16929133858267717


In [95]:
print("Median precip on summer days (inches): ", np.median(summ2[summer]))
print("Maximum precip on summer days (inches): ", np.max(summ2[summer]))
summ2_rainy=summ2>0
print("Median precip on non-summer rainy days (inches): ", np.median(summ2[summ2_rainy & ~summer]))

Median precip on summer days (inches):  0.0
Maximum precip on summer days (inches):  1.0905511811023623
Median precip on non-summer rainy days (inches):  0.11023622047244094


In [96]:
print("Median precip on summer days (inches): ", np.median(summ3[summer]))
print("Maximum precip on summer days (inches): ", np.max(summ3[summer]))
summ3_rainy=summ3>0
print("Median precip on non-summer rainy days (inches): ", np.median(summ3[summ3_rainy & ~summer]))

Median precip on summer days (inches):  0.0
Maximum precip on summer days (inches):  0.8503937007874016
Median precip on non-summer rainy days (inches):  0.20078740157480315
